[package]
name = "transmogrify"
version = "0.2.0"
description = "Zero-cost downcasting for limited compile-time specialization."
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
license = "MIT"
keywords = ["specialization"]
categories = ["no-std", "rust-patterns"]
repository = "https://github.com/sagebind/transmogrify"
edition = "2018"
